### ISSUE TITLE
[Question] Producing side-effects on page initialization

### ISSUE THREAD

**Issue by stan-kroon** [martinmoec/Fable.ReactNative.Navigation#2]
Hey martinmoec,

Thanks for these bindings! I'm using them in a project, and I was wondering how you would produce side-effects on page initialization. Coming from an Fable-Elmish background, I used to create side-effects (for example, fetching some data from a remote server) in the init method, like this:

`let init (SomeData: ModelData): Model * Cmd<Msg> =`
`    { SomeModel = SomeData}, Cmd.OfAsync.perform Api.SomeHttpMethod SomeMsg`

The 'SomeMsg' would then be handled by the update function.

Now I'm using the react hook to create a similar MVU architecture, as shown in your how-to. However, I can't figure out how to produce side effects on page initialization in a nice way. Currently, I'm producing these side-effects by using an if statement in the view, and running the side effects on the first view render, but it just doesn't feel that idiomatic.

Any advice on how you would tackle this problem would be appreciated!

**Comment by martinmoec** [comment]
Hi!
I'm personally using React hooks, like you mention you do. As someone who also come from a Fable-Elmish background i found using the useEffect hook to be a good alternative to the "init commands". Here is a simplified example of how i fetch some data on page initialization:
```fsharp

type Model = { SomeData : string option }
type Message = | FetchResponse of string

let init () = {SomeData = None}

let update model msg =
    match msg with
    | FetchResponse x -> {model with SomeData = Some x}

let fetchData dispatch =
    promise {
        let res = // perform some fetch request and store result
        dispatch (FetchResponse res)
    }

let view model dispatch = ...

let render () =
    Fable.React.FunctionComponent.Of (fun () ->
        let initialModel = init ()
        let model, dispatch = useReducer(update, initialModel)
        useEffect(fun _ ->
            fetchData dispatch
            |> Promise.start
        , [||])

        view model dispatch
    ) ()

```

Providing the useEffect hook with an empty array is equivalent to running its content only on component creation. So when the page is loaded onto the stack, the useEffect hook will fire once with our promise which will fetch some data. Once the fetch is completed we dispatch a new message with the result.

I personally like to use the Thoth.Fetch and Thoth.Json libraries with all my requests, as i find it to be a pretty smooth solution. For instance fetching a record type based on an ID:
```fsharp
type SomeDataType = {
    Id : int
    Value : string
}

...

type Message = | FetchResponse of Result<SomeDataType, FetchError>

...

let fetchData someId dispatch =
    promise {
        let requestPath =
             sprintf "/api/my-endpoint/%i" someId
        let decoder = Decode.Auto.generateDecoder<SomeDataType>()
        let! res = Fetch.tryGet(requestPath, decoder=decoder, properties=[])
        dispatch (FetchResponse res)
    }

...

// screen function called with some argument (example an user profile for user with id=uId)
let render (nav:INavigation<int>) =
    Fable.React.FunctionComponent.Of (fun (props:{|uId:int|}) ->
        let initialModel = init ()
        let model, dispatch = useReducer(update, initialModel)
        useEffect(fun _ ->
            fetchData props.uId dispatch
            |> Promise.start
        , [||])

        view model dispatch
    ) {|uId=nav.route.params|}
```

**Comment by stan-kroon** [comment]
Thank you for the detailed explanation! This is exactly what I was looking for.
