### ISSUE TITLE
Can't use Stack.NavigatorProps.HeaderMode

### ISSUE THREAD

**Issue by playfulThinking** [martinmoec/Fable.ReactNative.Navigation#3]
I have:
```
let StackNavigator = Stack.CreateStackNavigator()

navigationContainer [] [
    StackNavigator.Navigator.navigator [
                                         Stack.NavigatorProps.InitialRouteName startScreen ] [
        StackNavigator.Screen.screen homeScreenName homeScreen [] []
        StackNavigator.Screen.screen loginScreenName loginScreen [] []
    ]
]
```

Which works fine. If I add HeaderMode to the navigator props:
```
[Stack.NavigatorProps.HeaderMode None
 Stack.NavigatorProps.InitialRouteName startScreen]
```
 the compiler says:
```
This expression was expected to have type
    'Stack.NavigatorHeaderMode'
but here has type
    ''a option'     (code 1)
```

Being an FSharp and Fable newbie, I suppose I'm doing something wrong, but can't for the life of me figure it out...

Thanks much for the lib!

**Comment by martinmoec** [comment]
It's most likely the compiler mistaking the `HeaderMode.None` property for `Option.None`. I should probably re-name the case and just add the compilename `none`. In your case, you can probably fix this by swapping `None` for `HedaerMode.None`:
```
[Stack.NavigatorProps.HeaderMode HeaderMode.None
 Stack.NavigatorProps.InitialRouteName startScreen]
```

**Comment by playfulThinking** [comment]
Thanks! 

When I try your suggestion the compiler says `The value, namespace, type or module 'HeaderMode' is not defined.`

If I try `Stack.NavigatorProps.HeaderMode Screen`, the compiler says `The value or constructor 'Screen' is not defined`

If I try `Stack.NavigatorProps.Mode NavigatorMode.Card`, the compiler says `NavigatorMode` is not defined.

The commonality _seems_ to be that HeaderMode and NavigatorMode are `[<StringEnum>]`, and the compiler thinks they're undefined. On the other hand, `InitialRouteName` is not a StringEnum and works fine.

Does this make sense to you?

**Comment by playfulThinking** [comment]
I've solved the problem! I was running 
  Fable 3.4
  Fable.Core 3.2.7. 

After updating to 
  Fable 3.7.5
  Fable.Core 3.6.2

It now works! (I did have to follow your suggestion and use `NavigatorHeaderMode.None`)

Thanks much for your help!
